Filtres opérationnels sur les recettes et  modification de la data po…
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #100
Opened 2024-01-29 15:55 UTC by Leslie2186

…ur retirer les sdfsffs et autres dfsffgfdg

2024-01-29 15:56 UTC, GreG6431 approved these changes

2024-01-29 16:13 UTC, valihna approved these changes

2024-01-30 08:27 UTC, aimach requested changes

2024-01-30 08:27 UTC, aimach commented on frontend/src/components/recipes/RecipeCard.jsx
> +        <select onChange={(e) => setSectionFilter(e.target.value)}>
créer un composant réutilisable

2024-01-30 09:33 UTC, Leslie2186 commented on frontend/src/components/recipes/RecipeCard.jsx
> +        <select onChange={(e) => setSectionFilter(e.target.value)}>
Fait

2024-01-30 09:34 UTC, GreG6431 submitted a review, later dismissed

2024-01-30 09:36 UTC, valihna submitted a review, later dismissed

2024-01-30 09:42 UTC, aimach requested changes

2024-01-30 09:42 UTC, aimach commented on frontend/src/components/recipes/RecipeSelect.jsx
> +  functionFilter: PropTypes.string.isRequired,
je ne crois pas que ce soit une string !

2024-01-30 09:42 UTC, aimach commented on frontend/src/components/recipes/RecipeCard.jsx
>  }
je commente ici à propos des propTypes ⬇️  : recipes n'est pas une string

2024-01-30 09:49 UTC, Leslie2186 commented on frontend/src/components/recipes/RecipeSelect.jsx
> +  functionFilter: PropTypes.string.isRequired,
Fait

2024-01-30 09:49 UTC, Leslie2186 commented on frontend/src/components/recipes/RecipeCard.jsx
>  }
Fait

2024-01-30 09:50 UTC, GreG6431 submitted a review, later dismissed

2024-01-30 09:50 UTC, valihna approved these changes

2024-01-30 10:03 UTC, valihna approved these changes

2024-01-30 10:03 UTC, ThibaudDps approved these changes

2024-01-30 10:04 UTC, merged