INgredients display + css + steps recipe
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #102
Opened 2024-01-30 14:49 UTC by ThibaudDps

2024-01-30 14:50 UTC, valihna approved these changes

2024-01-30 14:50 UTC, Leslie2186 approved these changes

2024-01-30 16:28 UTC, jujuck requested changes

2024-01-30 16:28 UTC, jujuck commented on frontend/src/components/ingredientDisplay/IngrDisplay.jsx
> +    quantity: PropTypes.string.isRequired,
number

2024-01-30 16:28 UTC, jujuck commented on frontend/src/components/ingredientDisplay/IngrDisplay.jsx
> +    <div>
fragment

2024-01-30 16:28 UTC, jujuck commented on frontend/src/pages/recipe/Recipe.jsx
> +  const { recipes, ingredients } = useLoaderData();
Faire le point sur les ingrédients par recette avec Valériane. Les datas sont dispo en DB

2024-01-30 16:28 UTC, jujuck commented on frontend/src/main.jsx
> +          const recipes = await connexion
Essaie de configurer ta recette en inner join pour récupérer les ingrédients liés en directs

2024-02-05 10:20 UTC, valihna approved these changes

2024-02-05 10:20 UTC, Leslie2186 approved these changes

2024-02-05 11:12 UTC, jujuck approved these changes

2024-02-05 11:12 UTC, merged