Feat profile fav
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #103
Opened 2024-01-30 15:46 UTC by valihna

2024-01-30 15:48 UTC, GreG6431 submitted a review, later dismissed

2024-01-30 15:48 UTC, ThibaudDps submitted a review, later dismissed

2024-01-30 15:49 UTC, Leslie2186 approved these changes

2024-01-30 15:58 UTC, ThibaudDps submitted a review, later dismissed

2024-01-30 15:59 UTC, Leslie2186 approved these changes

2024-01-30 15:59 UTC, GreG6431 approved these changes

2024-01-30 16:37 UTC, jujuck requested changes

2024-01-30 16:37 UTC, jujuck commented on frontend/src/components/favorite/Favorite.jsx
> +        .get("/favorites", infosUser.auth_id)
Pas besoin du infos user

2024-01-30 16:37 UTC, jujuck commented on frontend/src/components/favorite/Favorite.jsx
> +  }, [infosUser.auth_id]);
Idem pas besoin de infosUsers

2024-01-30 16:37 UTC, jujuck commented on frontend/src/components/favorite/Hearth.jsx
> +  recipId: PropTypes.shape.isRequired,
A vérifer je pense que l'on a number et boolean et non shape

2024-01-30 16:42 UTC, valihna commented on frontend/src/components/favorite/Favorite.jsx
> +  }, [infosUser.auth_id]);
c'est ok :)

2024-01-31 07:29 UTC, ThibaudDps approved these changes

2024-01-31 07:59 UTC, GreG6431 approved these changes

2024-01-31 08:00 UTC, Leslie2186 approved these changes

2024-01-31 08:00 UTC, GreG6431 approved these changes

2024-02-02 15:55 UTC, jujuck approved these changes

2024-02-02 15:55 UTC, merged