Création formulaire recipe + CSS
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #104
Opened 2024-01-30 16:20 UTC by GreG6431

2024-01-30 16:20 UTC, ThibaudDps approved these changes

2024-01-30 16:22 UTC, Leslie2186 submitted a review, later dismissed

2024-01-30 16:41 UTC, jujuck requested changes

2024-01-30 16:41 UTC, jujuck commented on frontend/src/components/formrecipes/FormRecipes.jsx
> +          <div>
Div inutile

2024-01-30 16:41 UTC, jujuck commented on frontend/src/components/formrecipes/FormRecipes.jsx
> +              <p className="label-text">Name : </p>
POurquoi un p dans un label, met la classe directement sur le label

2024-01-30 16:41 UTC, jujuck commented on frontend/src/components/ingredientselect/IngredientSelect.jsx
> +        <p>Ingredients :</p>
Idem

2024-01-30 16:41 UTC, jujuck commented on frontend/src/components/ingredientselect/IngredientSelect.jsx
> +  index: PropTypes.string.isRequired,
number ???

2024-01-30 16:41 UTC, jujuck commented on frontend/src/pages/AddRecipes.jsx
> +    <div>
composant inutile

2024-02-05 08:46 UTC, GreG6431 commented on frontend/src/components/ingredientselect/IngredientSelect.jsx
> +  index: PropTypes.string.isRequired,
Ok

2024-02-05 09:25 UTC, GreG6431 commented on frontend/src/components/formrecipes/FormRecipes.jsx
> +              <p className="label-text">Name : </p>
Ok

2024-02-05 09:33 UTC, GreG6431 commented on frontend/src/components/ingredientselect/IngredientSelect.jsx
> +        <p>Ingredients :</p>
Ok

2024-02-05 10:34 UTC, GreG6431 commented on frontend/src/pages/AddRecipes.jsx
> +    <div>
Ok

2024-02-05 10:52 UTC, Leslie2186 approved these changes

2024-02-05 10:53 UTC, ThibaudDps approved these changes

2024-02-05 11:10 UTC, jujuck approved these changes

2024-02-05 11:10 UTC, merged