Initialisation des tables Auth, Regimes et User
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #45
Opened 2023-12-15 15:44 UTC by Leslie2186

2023-12-15 15:46 UTC, valihna approved these changes

2023-12-15 15:49 UTC, valihna approved these changes

2023-12-19 08:32 UTC, aimach requested changes
Change in db and seed

2023-12-19 08:46 UTC, ThibaudDps approved these changes

2023-12-19 08:50 UTC, aimach approved these changes

2023-12-19 08:51 UTC, merged