Feat dashbord user get
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #50
Opened 2023-12-20 10:30 UTC by Leslie2186

2023-12-20 10:36 UTC, valihna approved these changes

2023-12-20 11:25 UTC, jujuck requested changes

2023-12-20 11:25 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +const deleteUser = async (req, res, next) => {
Nom de la methode incorrecte : juste delete

2023-12-20 11:25 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +    res.json(users);
mettre un status 200

2023-12-20 11:25 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +    console.info(users);
PAS DE CONSOLE INFO OU RESTE DE TRUC !!!

2023-12-20 11:25 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +      res.json(item);
mettre un status(200)

2023-12-20 11:25 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +    if (item == null) {
Comme ce matin  à la démo, item est il équivalent à null ???

2023-12-20 11:25 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +  const putUser = req.body;
variable, just user

2023-12-20 11:25 UTC, jujuck commented on backend/src/app.js
>  // app.use(express.text());
Décommenter également le module de gestion des erreurs et passer un res.sendStatus(500). Sinon, l'utilisateur va récupérer l'erreur et peut l'analyser (faille de sécu)

2023-12-20 11:25 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +const add = async (req, res, next) => {
A commenter

2023-12-20 11:25 UTC, jujuck commented on backend/src/models/UserManager.js
> +    // Call the constructor of the parent class (AbstractManager)
Commente les methodes non utilisées

2023-12-20 11:25 UTC, jujuck commented on backend/src/router.js
> +router.delete("/users/:id", userControllers.deleteUser);
Attention au nom de la fonction

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/dashboard/Dashboard.jsx
> +import React from "react";
A retirer

2023-12-20 11:25 UTC, jujuck commented on frontend/src/main.jsx
> +        path: "/administration/management",
Ne pas doubler administration

2023-12-20 11:25 UTC, jujuck commented on frontend/src/main.jsx
> +      {
Supprimer le dashboard qui ne sert pour le moment à rien

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/navbarAdmin/NavbarAdmin.jsx
> +        <Link to="/administration">
A retirer

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/management/Management.jsx
> +      <div className="recipeManagement">
A retirer car ne sert à rien aujourd'hui

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.css
> +.tableUserManagement table {
A uniformiser sur le nomenclature des classes CSS

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.css
> +.buttonDelete,
C'est pas dans le bon fichier

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +import axios from "axios";
Mettre un service de connexion en plus

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +      console.info(myUsers);
Pas de console info

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +      console.error(error);
Mettre en place un message USER (Installer toastify)

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +            Username :{" "}
supprimer l'espace mort

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +            Birthday :{" "}
supprimer l'espace mort

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +            Picture :{" "}
supprimer l'espace mort

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +            Regime :{" "}
supprimer l'espace mort

2023-12-20 11:25 UTC, jujuck commented on frontend/src/components/usermanagement/UserManagement.jsx
> +    const form = document.querySelector(".form");
Remplacer par un state de control

2023-12-20 16:22 UTC, ThibaudDps submitted a review, later dismissed

2023-12-21 09:48 UTC, valihna approved these changes

2023-12-21 09:50 UTC, ThibaudDps approved these changes

2023-12-21 10:10 UTC, aimach requested changes

2023-12-21 10:10 UTC, aimach commented on frontend/src/pages/admin/Admin.jsx
> +      <h1>Dashboard</h1>
plutôt un h2 !

2023-12-21 10:30 UTC, ThibaudDps approved these changes

2023-12-21 10:33 UTC, valihna approved these changes

2023-12-21 10:37 UTC, aimach approved these changes

2023-12-21 10:38 UTC, merged