Feat component design
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #51
Opened 2023-12-20 16:38 UTC by ThibaudDps

2023-12-20 17:23 UTC, valihna submitted a review, later dismissed

2023-12-22 11:38 UTC, valihna submitted a review, later dismissed

2023-12-22 11:39 UTC, Leslie2186 approved these changes

2023-12-22 12:58 UTC, jujuck requested changes

2023-12-22 12:58 UTC, jujuck commented on frontend/src/pages/Home/Home.jsx
> +        <div className="square-img-text">
Cette section est utilisée 2 fois, faire un composant avec props

2024-01-03 15:36 UTC, ThibaudDps commented on frontend/src/pages/Home/Home.jsx
> +        <div className="square-img-text">
Component crée + librairie svg

2024-01-03 15:40 UTC, Leslie2186 approved these changes

2024-01-04 13:54 UTC, valihna submitted a review, later dismissed

2024-01-04 16:42 UTC, jujuck requested changes

2024-01-04 16:42 UTC, jujuck commented on frontend/src/pages/Home/Home.jsx
> +              className="Line"
Class css avec un nom en majuscule ?

2024-01-04 16:42 UTC, jujuck commented on package-lock.json
Le package-lock.json du global ne doit pas être dans un PR ?

2024-01-04 16:42 UTC, jujuck commented on package-lock.json
> +      "dependencies": {
Toastify est une dépendance de React

2024-01-04 16:42 UTC, jujuck commented on frontend/src/components/FrameSvgText/FrameSvgText.jsx
> +          className="Line"
ClassName avec une majuscule ?

2024-01-05 09:39 UTC, Leslie2186 approved these changes

2024-01-05 09:39 UTC, valihna approved these changes

2024-01-05 10:42 UTC, jujuck approved these changes

2024-01-05 10:42 UTC, merged