Feat sign up user
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #59
Opened 2024-01-04 16:03 UTC by Leslie2186

2024-01-04 16:04 UTC, ThibaudDps approved these changes

2024-01-04 16:05 UTC, valihna approved these changes

2024-01-04 16:23 UTC, jujuck requested changes

2024-01-04 16:23 UTC, jujuck commented on backend/seed.js
> +/*
Question, est ce fonctionnel ?

2024-01-05 11:36 UTC, valihna submitted a review, later dismissed

2024-01-05 12:49 UTC, GreG6431 approved these changes

2024-01-05 14:52 UTC, jujuck requested changes

2024-01-05 14:52 UTC, jujuck commented on backend/src/models/AuthManager.js
> +      `SELECT  * FROM ${this.table} WHERE mail = ?`,
Un espace en trop

2024-01-05 14:52 UTC, jujuck commented on frontend/src/pages/signUp/SignUp.css
> +.listeRegime select {
En anglais, il n'y a pas de e à list et respect de la convention de nommage avec -

2024-01-05 14:52 UTC, jujuck commented on frontend/src/pages/signUp/SignUpUser.jsx
>      toast.success("Les données ont bien été enregistrée !", {
Les données ont bien été enregistréeS et message en anglais

2024-01-05 14:52 UTC, jujuck commented on frontend/src/pages/signUp/SignUpUser.jsx
> +            Votre regime alimentaire
En anglais

2024-01-05 15:16 UTC, Leslie2186 commented on frontend/src/pages/signUp/SignUp.css
> +.listeRegime select {
ok

2024-01-05 15:31 UTC, Leslie2186 commented on frontend/src/pages/signUp/SignUpUser.jsx
>      toast.success("Les données ont bien été enregistrée !", {
ok

2024-01-05 15:42 UTC, valihna approved these changes

2024-01-05 15:42 UTC, ThibaudDps submitted a review, later dismissed

2024-01-05 15:57 UTC, aimach requested changes

2024-01-05 15:57 UTC, aimach commented on frontend/src/pages/signUp/SignUpUser.jsx
> +            Votre regime alimentaire
a mettre en angalis

2024-01-05 15:57 UTC, aimach commented on frontend/src/pages/signUp/SignUpUser.jsx
> +              <option value={0}>Choisir une option</option>
à mettre en anglais

2024-01-08 11:24 UTC, Leslie2186 commented on frontend/src/pages/signUp/SignUpUser.jsx
> +            Votre regime alimentaire
ok

2024-01-08 11:24 UTC, Leslie2186 commented on frontend/src/pages/signUp/SignUpUser.jsx
> +              <option value={0}>Choisir une option</option>
ok

2024-01-08 13:39 UTC, jujuck requested changes

2024-01-08 13:39 UTC, jujuck commented on frontend/src/pages/logIn/LogIn.jsx
> +            <button type="submit" className="button-sumbit-login">
Il y a une erreur dans le nom du CSS

2024-01-08 13:39 UTC, jujuck commented on backend/src/models/AuthManager.js
> +  async read() {
A supprimer

2024-01-08 13:39 UTC, jujuck commented on backend/src/controllers/authControllers.js
>  const read = async (req, res, next) => {
A supprimer

2024-01-08 13:41 UTC, merged