Feat recipe page
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #62
Opened 2024-01-05 10:31 UTC by valihna

2024-01-05 10:42 UTC, GreG6431 submitted a review, later dismissed

2024-01-05 10:49 UTC, Leslie2186 approved these changes

2024-01-05 11:21 UTC, aimach requested changes

2024-01-05 11:21 UTC, aimach commented on backend/seed.js
> +// eslint-disable-next-line no-unused-vars
enlever commentaire

2024-01-05 11:21 UTC, aimach commented on backend/database/schema.sql
> +  recipe VARCHAR(255) not null,
mettre title

2024-01-05 11:21 UTC, aimach commented on backend/src/controllers/recipeControllers.js
> +    .query("SELECT * FROM recipe")
il faut faire un manager

2024-01-05 11:21 UTC, aimach commented on backend/src/controllers/recipeControllers.js
> +const getRecipe = (req, res) => {
renomer en browse

2024-01-05 11:21 UTC, aimach commented on backend/src/controllers/recipeControllers.js
> +const getRecipeByID = (req, res) => {
renommer en read

2024-01-05 11:21 UTC, aimach commented on backend/src/controllers/recipeControllers.js
> +      // console.log(result[0][0]);
enlever commentaire

2024-01-05 11:21 UTC, aimach commented on backend/src/router.js
> +/* eslint-disable no-undef */
résoudre erreur eslint

2024-01-05 11:21 UTC, aimach commented on frontend/src/components/recipes/RecipeCard.jsx
> +    // eslint-disable-next-line react/jsx-filename-extension
corriger erreur eslint

2024-01-05 11:21 UTC, aimach commented on frontend/src/components/recipes/RecipeCard.jsx
> +// import { useLoaderData } from "react-router-dom";
enlever si inutile

2024-01-05 11:21 UTC, aimach commented on frontend/src/components/recipes/RecipeList.jsx
> +/* eslint-disable react/prop-types */
corriger erreur eslint

2024-01-05 11:21 UTC, aimach commented on frontend/src/main.jsx
> +// eslint-disable-next-line import/order
corriger erreur eslint

2024-01-05 11:21 UTC, aimach commented on frontend/src/pages/Recipes.jsx
> +  // eslint-disable-next-line no-unreachable
corriger erreur eslint

2024-01-05 11:21 UTC, aimach commented on frontend/src/components/recipes/RecipeList.jsx
> +  const recipes = [
il faut afficher les recettes que tu reçois de ton back

2024-01-05 11:21 UTC, aimach commented on frontend/src/components/recipes/RecipeList.jsx
> +// picture, section, name, preparation_time, cooking_time, difficulty, allergen
enlever ce commentaire

2024-01-05 11:21 UTC, aimach commented on frontend/src/pages/Recipes.jsx
> +    <RecipesCard />
il faut bien nommer ses composants

2024-01-09 09:34 UTC, valihna commented on backend/seed.js
> +// eslint-disable-next-line no-unused-vars
ok

2024-01-09 09:40 UTC, valihna commented on backend/src/controllers/recipeControllers.js
> +const getRecipeByID = (req, res) => {
C'est fait

2024-01-09 10:35 UTC, valihna commented on backend/database/schema.sql
> +  recipe VARCHAR(255) not null,
C'est fait

2024-01-09 15:10 UTC, valihna commented on backend/src/controllers/recipeControllers.js
> +    .query("SELECT * FROM recipe")
C'est fait

2024-01-09 16:18 UTC, Leslie2186 submitted a review, later dismissed

2024-01-09 16:19 UTC, ThibaudDps submitted a review, later dismissed

2024-01-09 16:32 UTC, jujuck requested changes

2024-01-09 16:32 UTC, jujuck commented on frontend/src/components/recipes/RecipeList.jsx
> +      <div>
A quoi sert la div ?

2024-01-09 16:32 UTC, jujuck commented on frontend/src/pages/Recipes.jsx
> +      <div>
A quoi sert la div

2024-01-09 16:35 UTC, valihna commented on frontend/src/pages/Recipes.jsx
> +      <div>
je l'ai retirée

2024-01-09 16:36 UTC, valihna commented on frontend/src/components/recipes/RecipeList.jsx
> +      <div>
ça y est je l'ai enlevée

2024-01-09 16:37 UTC, jujuck approved these changes

2024-01-09 16:37 UTC, merged