css recettes et ajout coeur favoris
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #74
Opened 2024-01-10 16:37 UTC by valihna

2024-01-10 16:42 UTC, ThibaudDps submitted a review, later dismissed

2024-01-10 16:48 UTC, GreG6431 submitted a review, later dismissed

2024-01-11 07:59 UTC, jujuck requested changes
Il me semble que la feature n'est pas finie. Ou est la partie Back End...
Le composant fav attend une props (recipID) et celle ci n'est jamais envoyé ?

2024-01-15 11:27 UTC, jujuck submitted a review, later dismissed

2024-01-15 11:27 UTC, jujuck commented on backend/database/schema.sql
> +  ingr_id INT NOT NULL,
C'est plutot un user_id

2024-01-15 11:27 UTC, jujuck commented on backend/src/controllers/favoriteControllers.js
> +    const favorite = await tables.favorite.readById(req.params.id);
C'est un readByUserId

2024-01-15 11:27 UTC, jujuck commented on backend/src/models/FavoriteManager.js
> +      `select * from ${this.table} WHERE id  = ? `,
where user_id

2024-01-15 11:27 UTC, jujuck commented on backend/src/models/FavoriteManager.js
> +      `INSERT INTO ${this.table} (recipe_id, ingr_id) VALUES (?, ?)`,
A mettre à jour

2024-01-15 11:27 UTC, jujuck commented on backend/src/router.js
> +router.post("/favorites", favoriteControllers.add);
Il manque un middleware de validation de données

2024-01-15 11:27 UTC, jujuck commented on frontend/src/components/favorite/Favorite.jsx
> +        .get(`${import.meta.env.VITE_BACKEND_URL}/api/favories`)
utilisation la connexion

2024-01-15 11:27 UTC, jujuck commented on frontend/src/components/favorite/Hearth.jsx
> +      await connexion.post("/favorites", id);
compléter avec un faux id de user
{ recipe_id: id, user_id: 1}

2024-01-23 13:45 UTC, Leslie2186 submitted a review, later dismissed

2024-01-23 13:49 UTC, GreG6431 approved these changes

2024-01-23 13:56 UTC, ThibaudDps approved these changes

2024-01-23 15:11 UTC, aimach approved these changes

2024-01-23 15:11 UTC, merged