Récupérer info user
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #76
Opened 2024-01-12 13:59 UTC by Leslie2186

2024-01-12 14:06 UTC, valihna submitted a review, later dismissed

2024-01-12 14:07 UTC, GreG6431 approved these changes

2024-01-15 11:10 UTC, jujuck submitted a review, later dismissed

2024-01-15 11:10 UTC, jujuck commented on frontend/src/pages/logIn/LogIn.jsx
> +      document.cookie = infosUser;
A supprimer

2024-01-15 11:10 UTC, jujuck commented on backend/src/controllers/authControllers.js
> +          .json({ id: login.id, email: login.mail, role: login.is_admin });
json({ connected : { id....}, user: {}})

2024-01-16 09:53 UTC, Leslie2186 commented on frontend/src/pages/logIn/LogIn.jsx
> +      document.cookie = infosUser;
ok

2024-01-16 11:11 UTC, Leslie2186 commented on backend/src/controllers/userControllers.js
> +const recup = async (req, res, next) => {
Retiré

2024-01-16 11:11 UTC, Leslie2186 commented on backend/src/controllers/authControllers.js
> +          .json({ id: login.id, email: login.mail, role: login.is_admin });
Fait

2024-01-16 15:11 UTC, GreG6431 submitted a review, later dismissed

2024-01-16 15:18 UTC, valihna approved these changes

2024-01-16 16:38 UTC, aimach requested changes

2024-01-16 16:38 UTC, aimach commented on backend/src/controllers/userControllers.js
> +const recup = async (req, res, next) => {
"recup" c'est pas très anglais... getByAuthId ? getUserConnected ?

2024-01-22 14:54 UTC, Leslie2186 commented on backend/src/controllers/userControllers.js
> +const recup = async (req, res, next) => {
supprimé

2024-01-22 14:57 UTC, valihna approved these changes

2024-01-22 14:59 UTC, GreG6431 approved these changes

2024-01-22 15:26 UTC, aimach approved these changes

2024-01-22 15:27 UTC, merged