Hotfix NavBar + mobile
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #80
Opened 2024-01-22 17:50 UTC by ThibaudDps

Hotfix css après ajout user picture
+ profil picture mobile

2024-01-23 09:16 UTC, valihna approved these changes

2024-01-23 12:41 UTC, Leslie2186 approved these changes

2024-01-23 16:15 UTC, aimach requested changes
des petites changements à faire !

2024-01-23 16:15 UTC, aimach commented on frontend/src/components/Navbar/Navbar.jsx
> +          {" "}
cet espace est-il nécessaire ?

2024-01-23 16:15 UTC, aimach commented on frontend/src/components/Navbar/Navbar.jsx
> +                <NavLink to="/administration/">Admin.</NavLink>
est-ce que le point à la fin est nécessaire ?

2024-01-23 16:15 UTC, aimach commented on frontend/src/components/Navbar/Navbar.jsx
> +          <div className="nav-pages">
l'enfant direct d'une balise ul doit être un li

2024-01-23 16:15 UTC, aimach commented on frontend/src/components/Navbar/Navbar.jsx
> +          <div className="nav-login">
l'enfant direct d'une balise ul doit être un li

2024-01-23 16:15 UTC, aimach commented on frontend/src/components/NavbarMobile/NavbarMobile.jsx
> +  const { connected } = useContext(AuthContext);
mettre sur la même ligne {connected, infosUser}

2024-01-24 08:39 UTC, GreG6431 approved these changes

2024-01-24 08:39 UTC, Leslie2186 approved these changes

2024-01-24 08:39 UTC, valihna approved these changes

2024-01-24 08:46 UTC, aimach approved these changes

2024-01-24 08:46 UTC, merged