Dashboard recipes
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #93
Opened 2024-01-25 16:22 UTC by Leslie2186

2024-01-25 16:28 UTC, ThibaudDps submitted a review, later dismissed

2024-01-25 16:29 UTC, valihna submitted a review, later dismissed

2024-01-25 16:44 UTC, aimach requested changes

2024-01-25 16:44 UTC, aimach commented on frontend/src/components/management/Management.jsx
> +  const userManagementVisible = () => {
pourquoi ne pas gérer le style avec un state et 2 classes CSS ?

2024-01-25 16:44 UTC, aimach commented on frontend/src/components/recipemanagement/RecipeManagement.jsx
> +              Modifier
modify ?

2024-01-26 09:26 UTC, valihna submitted a review, later dismissed

2024-01-26 09:27 UTC, GreG6431 submitted a review, later dismissed

2024-01-26 09:35 UTC, ThibaudDps submitted a review, later dismissed

2024-01-26 09:38 UTC, aimach requested changes

2024-01-26 09:38 UTC, aimach commented on frontend/src/components/recipemanagement/RecipeManagement.jsx
> +    toast.success("Les données ont bien été modifiée !", {
Mettre le message en anglais 🇬🇧

2024-01-26 09:38 UTC, aimach commented on frontend/src/components/recipemanagement/RecipeManagement.jsx
> +    toast.error("Il y a eu une erreur les données n'ont pas été modifiée !", {
Mettre le message en anglais 🇬🇧

2024-01-26 09:48 UTC, GreG6431 approved these changes

2024-01-26 09:50 UTC, ThibaudDps approved these changes

2024-01-26 09:55 UTC, aimach approved these changes

2024-01-26 09:55 UTC, merged