Ingredientmanagement
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam pull request #94
Opened 2024-01-25 16:22 UTC by GreG6431

2024-01-25 16:31 UTC, Leslie2186 approved these changes

2024-01-25 16:31 UTC, valihna approved these changes

2024-01-25 16:31 UTC, ThibaudDps approved these changes

2024-01-25 16:48 UTC, aimach requested changes

2024-01-25 16:48 UTC, aimach commented on frontend/src/components/ingredientmanagement/IngredientManagement.jsx
> +              Modifier
Modify

2024-01-25 16:48 UTC, aimach commented on frontend/src/components/management/Management.jsx
> +    const dashboardIngredient = document.querySelector(".dashboard-ingredient");
pourquoi ne pas avoir utilisé un state et 2 classes CSS ?

2024-01-26 09:05 UTC, GreG6431 commented on frontend/src/components/ingredientmanagement/IngredientManagement.jsx
> +              Modifier
Fait

2024-01-26 09:27 UTC, valihna approved these changes

2024-01-26 09:35 UTC, ThibaudDps approved these changes

2024-01-26 09:40 UTC, aimach requested changes

2024-01-26 09:40 UTC, aimach commented on frontend/src/components/ingredientmanagement/IngredientManagement.jsx
> +    toast.success("Les données ont bien été modifiée !", {
Mettre le message en anglais 🇬🇧

2024-01-26 09:40 UTC, aimach commented on frontend/src/components/ingredientmanagement/IngredientManagement.jsx
> +    toast.error("Il y a eu une erreur les données n'ont pas été modifiée !", {
Mettre le message en anglais 🇬🇧

2024-01-26 09:40 UTC, aimach commented on frontend/src/components/ingredientmanagement/IngredientManagement.jsx
> +              Modifier
C'est toujours "Modifier"

2024-01-26 09:53 UTC, Leslie2186 submitted a review, later dismissed

2024-01-26 09:53 UTC, ThibaudDps approved these changes

2024-01-26 10:32 UTC, Leslie2186 approved these changes

2024-01-26 10:33 UTC, aimach approved these changes

2024-01-26 10:33 UTC, merged